add warning on failed sensor update

diff --git a/mariadb/rootfs/etc/periodic/5min/5min-reporting b/mariadb/rootfs/etc/periodic/5min/5min-reporting
--- a/mariadb/rootfs/etc/periodic/5min/5min-reporting
+++ b/mariadb/rootfs/etc/periodic/5min/5min-reporting
@@ -5,4 +5,6 @@
 # ==============================================================================
 
 # Always successful, but preserv error messages
-report-sensors || true
+if ! report-sensors; then
+    bashio::log.warning "Failed to report diagnostic sensor values"
+fi
